---
- name: set keystone_admin_password
  lineinfile:
    path: /etc/kolla/globals.yml
    regexp: '^\s*#?\s*{{ item.name }}:'
    line: '{{ item.name }}: {{ item.value }}'
  with_items: "{{ globals_config }}"

- name: set kolla_internal_vip_address
  lineinfile:
    path: /etc/kolla/globals.yml
    regexp: '^\s*#?\s*kolla_internal_vip_address'
    line: 'kolla_internal_vip_address: "{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}"'
