---
- name: restart machine
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  ignore_errors: true
  listen: restart machine

- name: disp hostvars
  become: no
  local_action: debug var=hostvars
  listen: restart machine

- name: disp hostname in local
  become: no
  local_action: debug var={{ inventory_hostname }}
  listen: restart machine

- name: disp hostname
  become: no
  debug:
    var: "{{ inventory_hostname }}"
  listen: restart machine

- name: waiting for server to come back
  become: no
  local_action:
    module: wait_for
    host: "{{ ansible_host }}"
    state: started
    delay: 10
    timeout: 300
  listen: restart machine